### ISSUE TITLE
Form/Products List

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#1]
### Value statement
As a user
I need a list of my cosmetic products with expiring dates
so that I know when to throw out products when they get bad.

### Description (Text, Scribble, Wireframe, Design)
<img width="227" alt="Bildschirmfoto 2020-07-02 um 14 58 29" src="https://user-images.githubusercontent.com/34010932/86361784-9f1e1b00-bc74-11ea-9d36-775f3e1edbe3.png"> <img width="227" alt="Bildschirmfoto 2020-07-02 um 14 58 53" src="https://user-images.githubusercontent.com/34010932/86361793-a34a3880-bc74-11ea-89a2-47b5e01509b3.png">

### Acceptance criteria
 
- [x] The second input is type date
- [x] The third input is type number with a min of 1 
- [x] When the button is clicked, the input fields should be cleared
- [x] Before the form is completed for the first time there should be a picture under the form where the list items will be later
- [x] After the form is completed for the first time, the picture should be replaced with the first list item
- [x] A list item consists of the product name, opening date, and expiration date

### Tasks
 
- [x]  Create a feature branch
- [x]  Install styled components
- [x]  Install storybook
- [x]  Install React Testing Library
- [x]  Delete default react setup
- [x]  Add global styles
- [x]  Create component Button
- [x]  Add styling to Button
- [x]  Create Button in Storybook
- [x]  Write test for Button
- [x]  Create component Form 
- [x]  Create Form in Storybook
- [x]  Add styling to Form
- [x]  Write test for Form
- [x]  Create component Products list
- [x]  Add styling to Products list
- [x]  Create Products list in Storybook
- [x]  Write test for Products list 
- [x]  Add components to the app (feature implementation with the state)
- [x]  Add missing styles
- [x]  Write integration tests w/ Cypress ?

### Size
medium
