### ISSUE TITLE
FormCards

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#17]
### Value statement
As a user
I want the form to be split in cards
so that I have a better experience while filling out the form.

### Description (Text, Scribble, Wireframe, Design)
<img width="251" alt="Bildschirmfoto 2020-07-20 um 15 32 27" src="https://user-images.githubusercontent.com/34010932/87943368-391bfb00-ca9e-11ea-8d16-7c5fef75c34c.png"> <img width="251" alt="Bildschirmfoto 2020-07-20 um 15 32 48" src="https://user-images.githubusercontent.com/34010932/87943396-4638ea00-ca9e-11ea-84b7-c5cb443aa6ef.png"> <img width="251" alt="Bildschirmfoto 2020-07-20 um 15 33 19" src="https://user-images.githubusercontent.com/34010932/87943449-594bba00-ca9e-11ea-85ae-63fa86bc2512.png"> <img width="251" alt="Bildschirmfoto 2020-07-20 um 15 34 11" src="https://user-images.githubusercontent.com/34010932/87943525-77b1b580-ca9e-11ea-9e13-1ca993a4e1b2.png"> <img width="251" alt="Bildschirmfoto 2020-07-20 um 15 34 41" src="https://user-images.githubusercontent.com/34010932/87943583-89935880-ca9e-11ea-9a97-554a9c17012b.png">

### Acceptance criteria
 
- [x]  The form should consist of 5 cards of every step of the process
- [x]  Every card should have a small navigation that indicates how the process is going
- [x]  After the process is done the user should come to the product list

### Tasks
 
- [x]  Create a feature branch
- [x]  Add cards to the form component
- [x]  Write test for the cards component
- [x]  Write integration tests w/ Cypress
- [x]  Add components to the app (feature implementation with the state)
- [x]  Add missing styles

### Size
medium
