### ISSUE TITLE
Sort

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#18]
### Value statement
As a user
I want a sorting function 
so that can search through my products better.

### Description (Text, Scribble, Wireframe, Design)
<img width="312" alt="Bildschirmfoto 2020-07-20 um 15 57 27" src="https://user-images.githubusercontent.com/34010932/87945950-b7c66780-caa1-11ea-9a34-f27efa9ef0f9.png"> <img width="312" alt="Bildschirmfoto 2020-07-20 um 16 00 40" src="https://user-images.githubusercontent.com/34010932/87946340-2a374780-caa2-11ea-85f5-9361ba34c5bc.png">

### Acceptance criteria
 
- [x]  The product page should have a sort icon
- [x]  click on the icon should open a sortPopover
- [x]  The popover should have 3 options: soon to expire, alphabetically, recently added

### Tasks
 
- [x]  Create a feature branch
- [x]  Add sortPopover component
- [x]  Write test for the popover
- [x]  Write integration tests w/ Cypress
- [x]  Add components to the app (feature implementation with the state)
- [x]  Add missing styles

### Size
medium
