### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#2]
### Value statement
As a user
I want a separate page for the form and the products list
so that I have a better overview.

### Description (Text, Scribble, Wireframe, Design)
<img width="223" alt="Bildschirmfoto 2020-07-02 um 15 23 52" src="https://user-images.githubusercontent.com/34010932/86364233-3042c100-bc78-11ea-96c0-8903f96afbc9.png"> <img width="223" alt="Bildschirmfoto 2020-07-02 um 15 24 02" src="https://user-images.githubusercontent.com/34010932/86364248-35077500-bc78-11ea-87c3-460d3732d510.png"> <img width="223" alt="Bildschirmfoto 2020-07-02 um 15 24 14" src="https://user-images.githubusercontent.com/34010932/86364265-39cc2900-bc78-11ea-8509-c0ab52042db9.png">

### Acceptance criteria
 
- [x] When the user opens the app for the first time he comes to the welcome page
- [x] The welcome page has an info text, picture, and an add button
- [x] When the add button is clicked, the form page is opened
- [x] The form page has 2 additional input fields (type text)
- [x] The add button transforms into the cancel button
- [x] When the cancel button is clicked the user comes back to the product page
- [x] When a product is added, it will appear on the product page and the info text and picture will disappear

### Tasks
 
- [x]  Create a feature branch
- [x]  Create form modal component
- [x]  Create add/cancel button component
- [x]  Create add/cancel button in Storybook
- [x]  Write component tests
- [x]  Add components to the app (feature implementation with the state)
- [x]  Add missing styles
- [x]  Write integration tests w/ Cypress 

### Size
medium
