### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#20]
### Value statement
As a user
I want a dashboard
so that can have a good overview of my products.

### Description (Text, Scribble, Wireframe, Design)
<img width="246" alt="Bildschirmfoto 2020-07-24 um 16 38 01" src="https://user-images.githubusercontent.com/34010932/88402907-0d658180-cdcc-11ea-857b-c08df970ddf0.png"> <img width="246" alt="Bildschirmfoto 2020-07-24 um 16 38 24" src="https://user-images.githubusercontent.com/34010932/88402947-1bb39d80-cdcc-11ea-864d-2010cd84069a.png">

### Acceptance criteria
 
- [x]  The app should have a dashboard and a product page
- [x]  The dashboard page should have 2 segments: Recently added and Expiring soon 

### Tasks
 
- [x]   Create a feature branch
- [x]   Add router to app.js
- [x]   Write navigation component
- [x]   Write dashboard component
- [x]   Write notFound component
- [x]   Write test for the navigation
- [x]   Write test for dashboard
- [x]   Write test for the notFound
- [x]   Write story for the navigation
- [x]   Write story for the dashboard
- [x]   Write story for the notFound
- [x]   Write integration tests w/ Cypress
- [x]   Add components to the app (feature implementation with the state)
- [x]   Add missing styles

### Size
medium
