### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#23]
### Value statement
As a user
I want an archive page
so that can have a good overview of my products.

### Description (Text, Scribble, Wireframe, Design)
<img width="233" alt="Bildschirmfoto 2020-07-28 um 15 19 26" src="https://user-images.githubusercontent.com/34010932/88670745-bcb09a00-d0e5-11ea-99c4-42bbc21e20f5.png"> <img width="233" alt="Bildschirmfoto 2020-07-28 um 15 26 50" src="https://user-images.githubusercontent.com/34010932/88671586-c4247300-d0e6-11ea-97e2-15d202f7ac7b.png">

### Acceptance criteria
 
- [x]  The app should have an archive page as a part of the products page
- [x]  When a product expires, a message should appear on the dashboard for moving the product to the archive
- [x]  When a product is moved to the archive a toaster should confirm the move

### Tasks
 
- [x]   Create a feature branch
- [x]   Write archive component
- [x]   Write archive message component
- [x]   Write toaster component
- [x]   Write a test for the archive
- [x]   Write a test for archive message
- [x]   Write a story for the archive
- [x]   Write a story for the archive message
- [x]   Write integration tests w/ Cypress
- [x]   Add components to the app (feature implementation with the state)
- [x]   Add missing styles

### Size
medium
