### ISSUE TITLE
Star rating

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#24]
### Value statement
As a user
I want a star rating
so that can keep better track of the products I use

### Description (Text, Scribble, Wireframe, Design)
<img width="242" alt="Bildschirmfoto 2020-07-28 um 15 40 57" src="https://user-images.githubusercontent.com/34010932/88673313-bd96fb00-d0e8-11ea-906d-6026eb81aef2.png"> <img width="246" alt="Bildschirmfoto 2020-07-28 um 15 44 15" src="https://user-images.githubusercontent.com/34010932/88673691-3433f880-d0e9-11ea-9415-3e73d2e65d18.png">

### Acceptance criteria
 
- [x]  The product list items should show a star rating
- [x]  In product details there should also be a star rating

### Tasks
 
- [x]   Create a feature branch
- [x]   Write star rating component
- [x]   Write a test for the star rating
- [x]   Write a story for the star rating
- [x]   Write integration tests w/ Cypress
- [x]   Add components to the app (feature implementation with the state)
- [x]   Add missing styles

### Size
small
