### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#25]
### Value statement
As a user
I want to be able to write comments about the products
so that can keep better track of the products I use

### Description (Text, Scribble, Wireframe, Design)
<img width="246" alt="Bildschirmfoto 2020-07-28 um 15 55 00" src="https://user-images.githubusercontent.com/34010932/88674956-b40e9280-d0ea-11ea-9fb4-33729f663f62.png"> <img width="246" alt="Bildschirmfoto 2020-07-28 um 15 55 22" src="https://user-images.githubusercontent.com/34010932/88674996-c092eb00-d0ea-11ea-9fff-4b854117a4d0.png"> <img width="246" alt="Bildschirmfoto 2020-07-28 um 15 55 54" src="https://user-images.githubusercontent.com/34010932/88675054-d3a5bb00-d0ea-11ea-8649-0c81a36fdde0.png">

### Acceptance criteria

- [x]  In product details there should also be a comment feature
- [x]  User should be able to edit a comment

### Tasks
 
- [x]   Create a feature branch
- [x]   Write a comment component
- [x]   Write a edit comment component
- [x]   Write a test for the comment
- [x]   Write a test for the edit comment
- [x]   Write a story for the comment
- [x]   Write a story for the edit comment
- [x]   Write integration tests w/ Cypress
- [x]   Add components to the app (feature implementation with the state)
- [x]   Add missing styles

### Size
medium
