### ISSUE TITLE
UsedUp

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#32]
### Value statement
As a user
I want to be able to label a product as used up
so that can keep better track of the products I use

### Description (Text, Scribble, Wireframe, Design)
<img width="246" alt="Bildschirmfoto 2020-08-06 um 15 36 45" src="https://user-images.githubusercontent.com/34010932/89538266-a51a9500-d7fa-11ea-8071-fe75babda8b7.png"> <img width="246" alt="Bildschirmfoto 2020-08-06 um 15 37 08" src="https://user-images.githubusercontent.com/34010932/89538317-b2378400-d7fa-11ea-8181-c5a8191996b7.png"> <img width="246" alt="Bildschirmfoto 2020-08-06 um 15 37 29" src="https://user-images.githubusercontent.com/34010932/89538362-be234600-d7fa-11ea-8ff7-dd732310ef50.png">

### Acceptance criteria

- [x]  In product details there should be a used up checkbox
- [x]  User should be able to input the date of when the product was used up
- [x]  After the used up-date is saved, a modal should appear and ask if the user wishes to put the product into the archive

### Tasks
 
- [x]   Create a feature branch
- [x]   Write a usedUp component
- [x]   Add usedUp date to edit component
- [x]   Write a test for the component
- [x]   Add the component to storybook 
- [x]   Write integration tests w/ Cypress
- [x]   Add components to the app (feature implementation with the state)
- [x]   Add missing styles

### Size
medium
