### ISSUE TITLE
LocalStorage/InfoPopover

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#4]
### Value statement
As a user
I want my entries to be saved
so that I can access them when I reload the site.

### Description (Text, Scribble, Wireframe, Design)
<img width="272" alt="Bildschirmfoto 2020-07-06 um 13 25 18" src="https://user-images.githubusercontent.com/34010932/86588517-2678d080-bf8c-11ea-9e3f-40baa070754e.png">

### Acceptance criteria
 
- [x] When the user reloads the app, the product list should be displayed 
- [x] On the form page there should be an Info Popover next to the month input that explains what the expiration month means

### Tasks
 
- [x]  Create a feature branch
- [x]  Install Popover
- [x]  Implement local storage
- [ ]  Write test for local storage
- [x]  Create info popover component
- [x]  Create popover component in Storybook
- [x]  Write component test
- [x]  Add components to the app (feature implementation with the state)
- [x]  Add missing styles
- [ ]  Write integration tests w/ Cypress 

### Size
small
