### ISSUE TITLE
Product details

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#7]
### Value statement
As a user
I want to have a details page
so that I have a better overview of my product.

### Description (Text, Scribble, Wireframe, Design)
<img width="268" alt="Bildschirmfoto 2020-07-13 um 15 38 55" src="https://user-images.githubusercontent.com/34010932/87310989-f8ad0200-c51e-11ea-948c-8ee154d71ead.png"> <img width="268" alt="Bildschirmfoto 2020-07-13 um 15 39 26" src="https://user-images.githubusercontent.com/34010932/87311054-0a8ea500-c51f-11ea-98e2-ac6151c5c30f.png">

### Acceptance criteria
 
- [x] Product items should be styled to communicate that they are clickable
- [x] When a product item is clicked a drawer opens with the product details

### Tasks
 
- [x]  Create a feature branch
- [x]  Change productItem styling
- [x]  Create productDetail component 
- [x]  Create productDetail in storybook
- [x]  Write test for productDetail component
- [x]  Write integration tests w/ Cypress
- [x]  Add components to the app (feature implementation with the state)
- [x]  Add missing styles

### Size
small
