### ISSUE TITLE
Edit product

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#8]
### Value statement
As a user
I want to be able to edit my products
so that I can change or add information about the products.

### Description (Text, Scribble, Wireframe, Design)
<img width="268" alt="Bildschirmfoto 2020-07-13 um 15 50 49" src="https://user-images.githubusercontent.com/34010932/87312282-a371f000-c520-11ea-930b-34bb8a941c17.png"> <img width="268" alt="Bildschirmfoto 2020-07-13 um 15 51 15" src="https://user-images.githubusercontent.com/34010932/87312327-b1c00c00-c520-11ea-90dc-56391b450d1b.png"> <img width="268" alt="Bildschirmfoto 2020-07-13 um 15 51 39" src="https://user-images.githubusercontent.com/34010932/87312376-c13f5500-c520-11ea-8d1d-980b68093559.png"> <img width="268" alt="Bildschirmfoto 2020-07-13 um 15 52 10" src="https://user-images.githubusercontent.com/34010932/87312414-d2886180-c520-11ea-8568-d5f7606b5ef7.png">

### Acceptance criteria
 
- [x]  Product items should have a menu icon 
- [x]  When the edit icon is clicked the user comes to the edit page
- [x]  On the details page there is also a menu icon that opens a popover 
- [x]  The popover has 2 options: edit and delete
- [x]  When the edit option is clicked the user comes to the edit page
- [x]  The edit pages opens the product details with input fields
- [x]  The input fields have the values of the product in them
- [x]  When the save button is clicked the user comes to the product details page with the edited product information

### Tasks
 
- [x]  Create a feature branch
- [x]  Add menu icon to product item and detail page
- [x]  Create editProduct component 
- [x]  Create editProduct in storybook
- [x]  Write test for editProduct component
- [x]  Create menuPopover component 
- [x]  Create menuPopover in storybook
- [x]  Write test for menuPopover component
- [x]  Write integration tests w/ Cypress
- [x]  Add components to the app (feature implementation with the state)
- [x]  Add missing styles

### Size
medium
