### ISSUE TITLE
Delete product

### ISSUE THREAD

**Issue by dianahime** [dianahime/capstone-project#9]
### Value statement
As a user
I want to be able to delete my products
so that I have better control over my product list.

### Description (Text, Scribble, Wireframe, Design)
<img width="255" alt="Bildschirmfoto 2020-07-13 um 16 09 14" src="https://user-images.githubusercontent.com/34010932/87314335-5a6f6b00-c523-11ea-8822-9dad9a547459.png"> <img width="258" alt="Bildschirmfoto 2020-07-20 um 15 25 27" src="https://user-images.githubusercontent.com/34010932/87942673-3f5da780-ca9d-11ea-8072-afe970a7641d.png">

### Acceptance criteria
 
- [x]  On the details page there is also a menu icon that opens a popover 
- [x]  The popover has 2 options: edit and delete
- [x]  When the delete option is clicked a modal is opened to confirm that the product should be deleted
- [x]  The modal has a question and delete and cancel buttons 
- [x]  When the user clicks cancel he returns to the product detail page
- [x]  When the user confirms the delete action he returns to the productList page
- [x]  The edit page also has a cancel button 
- [x]  When the button is clicked the productDetails page is opened

### Tasks
- [x]  Create a feature branch
- [x]  Add menu icon to product item and detail page
- [x]  Create delete function 
- [x]  Create deleteModal component
- [x]  Create deleteModal in storybook
- [x]  Write test for deleteModal component
- [x]  Write integration tests w/ Cypress
- [x]  Add missing styles

### Size
small
